version: '2'

services:
    scrapy:
        image: daocloud.io/jsongo/scrapy:latest 
        container_name: scrapy 
        #restart: always
        environment:
            VERSION: 1.0.0
            #LISTEN_PORT: 8960
        #network_mode: host
        ports:
            - 8960:8600
        working_dir: /code
        volumes:
            - /data/scrapy/code/trip:/code
            - /data/scrapy/logs:/var/lib/scrapyd/logs
            - /data/scrapy/dbs:/var/lib/scrapyd/dbs
            - /data/scrapy/code/travel:/var/lib/scrapyd/items
